# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 XMV Solutions GmbH
# SPDX-FileContributor: David Koller <david.koller@xmv.de>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-manager-webhook-hcloud-zones.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager-webhook-hcloud-zones.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cert-manager-webhook-hcloud-zones.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cert-manager-webhook-hcloud-zones.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "cert-manager-webhook-hcloud-zones.serviceAccountName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "cert-manager-webhook-hcloud-zones.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port=8443
            - --v=2
          env:
            - name: GROUP_NAME
              value: {{ .Values.groupName | quote }}
            - name: SOLVER_NAME
              value: {{ .Values.solverName | quote }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
            {{- with .Values.livenessProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
            {{- with .Values.readinessProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: serving-certs
              mountPath: /tls
              readOnly: true
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: serving-certs
          secret:
            secretName: {{ include "cert-manager-webhook-hcloud-zones.servingCertificate" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
