# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 XMV Solutions GmbH
# SPDX-FileContributor: David Koller <david.koller@xmv.de>
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-webhook-hcloud-zones.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager-webhook-hcloud-zones.labels" . | nindent 4 }}
{{- with .Values.image.pullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
